import { JetBrains_Mono } from "next/font/google";
import "./globals.css";

import {FaGithub, FaTwitter, FaLinkedind} from 'react-icons/fi'


//components
import Header from "@/components/Header";
import PageTransition from "@/components/PageTransition";
import StairTransition from "@/components/StairTransition";
import { icons } from "lucide-react";


const jetBrains_Mono = JetBrains_Mono({ 
  subsets: ["latin"], 
  weight: ["100", "200", "300", "400", "500", "600", "700","800"],
  Variable: '--font-jetbrainsMono',
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={jetBrains_Mono.Variable}>
        <Header />
        <StairTransition />
        <PageTransition>
          {children}
        </PageTransition>
       <footer className="text-center justify-center flex  w-full h-full  text-accent bg-transparent mt-10" >
        2024 @copyright Desgin by me 
       </footer>
        </body>
    </html>
  );
}
